Numpy array

In [10]:
python_list = [1,2,3,4,5]
print('Type :',type(python_list))
print(python_list)

Type : <class 'list'>
[1, 2, 3, 4, 5]


Two Dimensional list

In [11]:
two_dimensional_list = [[0,1,2],[3,4,5],[6,7,8]]
print(two_dimensional_list)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


Two Dimensional list using Numpy

In [12]:
import numpy as np

numpy_array_from_list = np.array(python_list)
print(type(numpy_array_from_list))
print(numpy_array_from_list)


<class 'numpy.ndarray'>
[1 2 3 4 5]


Float Numpy

In [13]:
python_list = [1,2,3,4,5]
numpy_array_from_list2 = np.array(python_list, dtype=float)
print(numpy_array_from_list2)

[1. 2. 3. 4. 5.]


Boolean numpy arrays

In [14]:
numpy_bool_array = np.array([0,1,-1,0,0], dtype=bool)
print(numpy_bool_array)

[False  True  True False False]


multidimensional array using numpy

In [15]:
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type(numpy_two_dimensional_list))
print(numpy_two_dimensional_list)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


numpy array to list

In [16]:
np_to_list = numpy_array_from_list.tolist()
print(type(np_to_list))
print('one dimensional array:',np_to_list)
print('two dimensional list:',numpy_two_dimensional_list.tolist())

<class 'list'>
one dimensional array: [1, 2, 3, 4, 5]
two dimensional list: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


Array from tuple

In [17]:
python_tuple = (1,2,3,4,5)
numpy_array_from_tuple= np.array(python_tuple)
print('numpy_array_from_tuple: ', numpy_array_from_tuple)

numpy_array_from_tuple:  [1 2 3 4 5]


Shape of numpy array

In [ ]:
nums = np.array([1,2,3,4,5])
print(nums)
print('shape of nums: ', nums.shape)
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list:', numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[0, 1, 2, 3],
                                [4,5,6,7],
                                [8,9,10, 11]])
print(three_by_four_array.shape)


[1 2 3 4 5]
shape of nums:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list: (3, 3)
(3, 4)


Data type of numpy array

In [25]:
int_lists = [-3, -2, -1, 0, 1, 2,3]
int_array=np.array(int_lists)
float_array=np.array(int_array, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)


[-3 -2 -1  0  1  2  3]
int64
[-3. -2. -1.  0.  1.  2.  3.]
float64


Size of a numpy array

In [28]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
two_dimensional_list = np.array([[0, 1, 2],
                              [3, 4, 5],
                              [6, 7, 8]])

print('The size:', numpy_array_from_list.size) 
print('The size:', two_dimensional_list.size)  

The size: 5
The size: 9


Getting items from a numpy array

In [30]:
# 2 Dimension Array
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0,:]
second_row = two_dimension_array[1,:]
third_row = two_dimension_array[2,:]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)
first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('First column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)

First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]
First column: [1 4 7]
Second column: [2 5 8]
Third column:  [3 6 9]
